export const incidents = [
  {
    id: "YL-2048",
    camera: "Park north entrance",
    location: "Block C community park",
    object: "Plastic bottle",
    time: "2 minutes ago",
    date: "9 Jun 2026, 1:42 PM",
    confidence: 86,
    status: "Needs review",
    zone: "Lawn boundary",
  },
  {
    id: "YL-2047",
    camera: "Market street 02",
    location: "Commercial lane",
    object: "Waste bag",
    time: "18 minutes ago",
    date: "9 Jun 2026, 1:26 PM",
    confidence: 81,
    status: "Needs review",
    zone: "Shop frontage",
  },
  {
    id: "YL-2046",
    camera: "Playground west",
    location: "Family park",
    object: "Paper cup",
    time: "43 minutes ago",
    date: "9 Jun 2026, 1:01 PM",
    confidence: 74,
    status: "Under review",
    zone: "Play area",
  },
  {
    id: "YL-2045",
    camera: "Main gate mobile",
    location: "Society entrance",
    object: "Food container",
    time: "1 hour ago",
    date: "9 Jun 2026, 12:33 PM",
    confidence: 78,
    status: "Confirmed",
    zone: "Visitor lane",
  },
  {
    id: "YL-2044",
    camera: "Street 08 corner",
    location: "Block A",
    object: "Plastic bag",
    time: "2 hours ago",
    date: "9 Jun 2026, 11:18 AM",
    confidence: 69,
    status: "False alert",
    zone: "Green belt",
  },
] as const;

export const cameras = [
  {
    id: "CAM-001",
    name: "Park north entrance",
    location: "Block C community park",
    type: "Webcam",
    status: "Online",
    lastSeen: "Live now",
    fps: "18 FPS",
    resolution: "720p",
    zones: 2,
  },
  {
    id: "CAM-002",
    name: "Market street 02",
    location: "Commercial lane",
    type: "CCTV / RTSP",
    status: "Online",
    lastSeen: "Live now",
    fps: "16 FPS",
    resolution: "1080p",
    zones: 1,
  },
  {
    id: "CAM-003",
    name: "Main gate mobile",
    location: "Society entrance",
    type: "Mobile",
    status: "Offline",
    lastSeen: "12 minutes ago",
    fps: "--",
    resolution: "720p",
    zones: 1,
  },
  {
    id: "CAM-004",
    name: "Playground west",
    location: "Family park",
    type: "Webcam",
    status: "Online",
    lastSeen: "Live now",
    fps: "20 FPS",
    resolution: "720p",
    zones: 2,
  },
  {
    id: "CAM-005",
    name: "Street 08 corner",
    location: "Block A",
    type: "Recorded demo",
    status: "Pending",
    lastSeen: "Not connected",
    fps: "--",
    resolution: "1080p",
    zones: 0,
  },
] as const;

export const members = [
  {
    name: "Ali Hassan",
    email: "ali@example.com",
    role: "Society admin",
    status: "Active",
    lastActive: "Now",
    initials: "AH",
  },
  {
    name: "Sara Khan",
    email: "sara@example.com",
    role: "Operator",
    status: "Active",
    lastActive: "8 minutes ago",
    initials: "SK",
  },
  {
    name: "Usman Tariq",
    email: "usman@example.com",
    role: "Operator",
    status: "Invited",
    lastActive: "Invitation sent",
    initials: "UT",
  },
] as const;

